# Generated by Django 6.0.4 on 2026-05-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organizer', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('latitude', models.FloatField(max_length=100)),
                ('longitude', models.FloatField(max_length=100)),
                ('eventDate', models.DateTimeField(verbose_name='Start Date')),
                ('endDate', models.DateTimeField(verbose_name='End Date')),
            ],
        ),
    ]
