# Generated by Django 6.0.4 on 2026-05-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(null=True, upload_to='event_images'),
        ),
    ]
