# Generated by Django 6.0.4 on 2026-05-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=200)),
                ('building', models.CharField(max_length=200)),
                ('room', models.IntegerField(max_length=4)),
                ('startTime', models.TimeField(verbose_name='Start Time')),
                ('endTime', models.TimeField(verbose_name='End Time')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
