# Generated by Django 6.0.4 on 2026-05-02 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('longitude', models.FloatField(max_length=100)),
                ('latitude', models.FloatField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='class',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.building'),
        ),
    ]
